<?php
/**
 * Advanced Custom Fields Fields
 *
 * This file contains all of the ACF fields used on the site.
 */
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_%c3%a5terblickar',
		'title' => 'Återblickar',
		'fields' => array (
			array (
				'key' => 'field_509d682ea2147',
				'label' => 'År',
				'name' => 'aterblick_ar',
				'type' => 'number',
				'instructions' => 'Vilket år är denna återblick för.
	ex. 2012',
				'required' => 1,
				'default_value' => '',
				'min' => '',
				'max' => '',
				'step' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_509d6d020c1d4',
				'label' => 'Introduktion',
				'name' => 'aterblick_introduktion',
				'type' => 'textarea',
				'instructions' => 'Skriv en kort paragraf introduktion till året och återblicken.',
				'default_value' => '',
				'formatting' => 'br',
				'maxlength' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_509d685fa2148',
				'label' => 'Beskrivning',
				'name' => 'aterblick_beskrivning',
				'type' => 'wysiwyg',
				'instructions' => 'Fyll i en kort beskrivning om året i fråga.',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
				'the_content' => 'yes',
			),
			array (
				'key' => 'field_509d70c79a80e',
				'label' => 'Huvudbild',
				'name' => 'aterblick_image',
				'type' => 'image',
				'instructions' => 'Ladda upp en huvudbild för återblicken.
	Storlek: 480px bred. Anpassa höjd efter innehåll.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_509d6896a2149',
				'label' => 'Länkar m.m',
				'name' => 'aterblick_lankarmm',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
				'the_content' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'aterblick',
					'order_no' => '0',
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_framsida',
		'title' => 'Framsida',
		'fields' => array (
			array (
				'key' => 'field_50826d7691776',
				'label' => 'Konferenstitel',
				'name' => 'home_title',
				'type' => 'text',
				'instructions' => 'Ange titeln på konferensen med år.
	ex. WebCoast 2013',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_50826d7691f4d',
				'label' => 'Konferensdatum',
				'name' => 'home_dates',
				'type' => 'text',
				'instructions' => 'Vilka datum äger konferensen rum?
	ex. 16-18 mars',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_50826df88310e',
				'label' => 'Biljettförsäljning igång?',
				'name' => 'home_forsaljning',
				'type' => 'true_false',
				'instructions' => 'Markera om biljettförsäljningen är igång eller inte.',
				'message' => 'Markera om biljettförsäljningen är igång eller inte.',
				'default_value' => 0,
			),
			array (
				'key' => 'field_1',
				'label' => 'Slutsålt?',
				'name' => 'home_slutsalt',
				'type' => 'true_false',
				'message' => 'Är biljetterna slut?',
				'default_value' => 0,
			),
			array (
				'key' => 'field_50826df8838fc',
				'label' => 'Länk till biljetter',
				'name' => 'home_ticket_link',
				'type' => 'text',
				'instructions' => 'Ange länken dit knappen för biljettköp skall ta besökare.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_50826ebebf259',
				'label' => 'Introduktionstext',
				'name' => 'home_introtext',
				'type' => 'textarea',
				'instructions' => 'Skriv en kort text om WebCoast här.
	(fältet tar inte HTML-kod)',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'none',
			),
			array (
				'key' => 'field_50826ebebfa34',
				'label' => 'Embedkod för film',
				'name' => 'home_movie_code',
				'type' => 'textarea',
				'instructions' => 'Fyll i embedkoden för den video som skall visas på framsidan.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_509b65ddb0187',
				'label' => 'Social Text',
				'name' => 'home_socialtext',
				'type' => 'text',
				'instructions' => 'Text som uppmanar till social kontakt. Visas längst ner på startsidan bredvid nyhetsbrevet.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-templates/template-frontpage.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_programinfo',
		'title' => 'Programinfo',
		'fields' => array (
			array (
				'key' => 'field_5184c8c8e588d',
				'label' => 'Programinfo',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_50ba170d7e088',
				'label' => 'Sammanfattning',
				'name' => 'program_summary',
				'type' => 'textarea',
				'instructions' => 'Sammanfatta denna programhändelse i en kort paragraf.',
				'default_value' => '',
				'formatting' => 'html',
				'maxlength' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_50827cfbcb992',
				'label' => 'Rum',
				'name' => 'program_location',
				'type' => 'text',
				'instructions' => 'Var äger händelsen rum?',
				'default_value' => '',
				'formatting' => 'none',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_50827cfbcc15c',
				'label' => 'Datum',
				'name' => 'program_date',
				'type' => 'date_picker',
				'instructions' => 'När äger händelsen rum?',
				'required' => 1,
				'date_format' => 'yy-mm-dd',
				'display_format' => 'yy-mm-dd',
				'first_day' => 1,
			),
			array (
				'key' => 'field_50827cfbcc935',
				'label' => 'Starttid',
				'name' => 'program_starttime',
				'type' => 'text',
				'instructions' => 'När börjar händelsen.
	ex. 09:00',
				'required' => 1,
				'default_value' => '',
				'formatting' => 'none',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_50827cfbcd106',
				'label' => 'Sluttid',
				'name' => 'program_endtime',
				'type' => 'text',
				'instructions' => 'När slutar händelsen.
	ex. 10:00',
				'default_value' => '',
				'formatting' => 'none',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_5184de133e369',
				'label' => 'Talare',
				'name' => 'program_talare',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5184de273e36a',
						'label' => 'Namn',
						'name' => 'program_talare_namn',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'formatting' => 'none',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array (
						'key' => 'field_5184de343e36b',
						'label' => 'URL',
						'name' => 'program_talare_url',
						'type' => 'text',
						'instructions' => 'Fyll i en URL till talarens profil. Exempelvis LinkedIn, Twitter m.m',
						'column_width' => '',
						'default_value' => '',
						'formatting' => 'none',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Lägg till talare',
			),
			array (
				'key' => 'field_50827f1fd2ecc',
				'label' => 'Talare',
				'name' => 'program_spaker',
				'type' => 'text',
				'instructions' => 'Fyll i vem som håller i händelsen.',
				'default_value' => '',
				'formatting' => 'none',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_5184c8dae588e',
				'label' => 'Video',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5184c9e16a1ad',
				'label' => 'Finns video?',
				'name' => 'video_exists',
				'type' => 'true_false',
				'message' => 'Finns videoinnehåll?',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5184c90be588f',
				'label' => 'Tumnagel',
				'name' => 'video_thumbnail',
				'type' => 'image',
				'instructions' => 'Ladda upp en tumnagel för videon. Tumnageln skall vara 300x169px.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5184c9e16a1ad',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5184c935e5890',
				'label' => 'Embedkod',
				'name' => 'video_embed',
				'type' => 'textarea',
				'instructions' => 'Ange embedkoden från videotjänsten. Spelaren skall vara 640px bred.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5184c9e16a1ad',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'formatting' => 'html',
				'maxlength' => '',
				'placeholder' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'program',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'revisions',
				4 => 'author',
				5 => 'format',
				6 => 'featured_image',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_sponsor-settings',
		'title' => 'Sponsor Settings',
		'fields' => array (
			array (
				'key' => 'field_527d5dd6dcb45',
				'label' => 'Sponsor Display Year',
				'name' => 'sponsor_display_year',
				'type' => 'number',
				'instructions' => 'Enter the year from which sponsors should be displayed.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 2013,
				'prepend' => '',
				'append' => '',
				'min' => 2010,
				'max' => '',
				'step' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_sponsorinfo',
		'title' => 'Sponsorinfo',
		'fields' => array (
			array (
				'key' => 'field_50826c6079920',
				'label' => 'Länk',
				'name' => 'sponsor_link',
				'type' => 'text',
				'instructions' => 'Fyll i länken till sponsorns hemsida.',
				'default_value' => '',
				'formatting' => 'none',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_50957ba2a50d3',
				'label' => 'Framsidebild',
				'name' => 'sponsor_fpimage',
				'type' => 'image',
				'instructions' => 'Ladda upp en bild för sponsorn på framsidan.
	200x200px på vit bakgrund, centrerad logo.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'sponsor',
					'order_no' => '0',
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_video',
		'title' => 'Video',
		'fields' => array (
			array (
				'key' => 'field_2',
				'label' => 'Beskrivning',
				'name' => 'video_beskrivning',
				'type' => 'textarea',
				'instructions' => 'Fyll i en kort beskrivning om vad sessionen handlade om.',
				'required' => 1,
				'default_value' => '',
				'formatting' => 'none',
				'maxlength' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_5',
				'label' => 'Talare',
				'name' => 'video_talare',
				'type' => 'repeater',
				'instructions' => 'Fyll i information om talaren/talarna.',
				'required' => 1,
				'sub_fields' => array (
					'field_6' => array (
						'key' => 'field_6',
						'label' => 'Namn',
						'name' => 'video_talare_namn',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'formatting' => 'none',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					'field_7' => array (
						'key' => 'field_7',
						'label' => 'Twitter URL',
						'name' => 'video_talare_twitter',
						'type' => 'text',
						'instructions' => 'Länk till talarens twitter, om sådan finns.',
						'column_width' => '',
						'default_value' => '',
						'formatting' => 'none',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Ny talare',
			),
			array (
				'key' => 'field_3',
				'label' => 'Embedkod',
				'name' => 'video_embedkod',
				'type' => 'textarea',
				'instructions' => 'Ange embedkoden från videotjänsten. Spelaren skall vara 640px bred.',
				'required' => 1,
				'default_value' => '',
				'formatting' => 'html',
				'maxlength' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_8',
				'label' => 'Tumnagel',
				'name' => 'video_tumnagel',
				'type' => 'image',
				'instructions' => 'Ladda upp en tumnagel för videon. Tumnageln skall vara 300x169px.',
				'required' => 1,
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'video',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_galleries',
		'title' => 'Galleries',
		'fields' => array (
			array (
				'key' => 'field_509e2b7d4fafb',
				'label' => 'Fotograf',
				'name' => 'galleries_fotograf',
				'type' => 'text',
				'default_value' => '',
				'formatting' => 'none',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portgallery',
					'order_no' => '0',
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
}